lib/comment_box_web/router.ex
defmodule CommentBoxWeb.Router do
  use CommentBoxWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CommentBoxWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index 

    resources "/comments", CommentController

    resources "/users", UserController

  end

  # Other scopes may use custom stacks.
  # scope "/api", CommentBoxWeb do
  #   pipe_through :api
  # end
end

lib/comment_box/application.ex
defmodule CommentBox.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(CommentBox.Repo, []),
      # Start the endpoint when the application starts
      supervisor(CommentBoxWeb.Endpoint, []),
      # Start your own worker by calling: CommentBox.Worker.start_link(arg1, arg2, arg3)
      # worker(CommentBox.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: CommentBox.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    CommentBoxWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/comment_box/comment.ex
defmodule CommentBox.Comment do
	
  	use Ecto.Schema
  	import Ecto.Changeset

	alias CommentBox.Repo
	alias CommentBox.Comment
	alias CommentBox.Users

	schema "comments" do
		field :title, :string
		field :text, :string
		field :owner, :integer
		field :parent, :integer

		timestamps()
	end

	@doc false
	def changeset(comment, attrs) do
		comment
		|> cast(attrs, [:title, :text, :owner, :parent])
	end


	@doc """
	Returns the list of comments.
	## Examples
	  iex> list_comments()
	  [%Comment{}, ...]
	
	"""

	def list_comments do
		Repo.all(Comment)
	end

	# def list_comments(owner) do
	# Repo.all(from(c in Comment, where: c.owner == ^owner.id))
	# end

	
	@doc """
	Gets a single comment.
	Raises `Ecto.NoResultsError` if the Comment does not exist.
	## Examples
	  iex> get_comment!(123)
	  %Comment{}
	  iex> get_comment!(456)
	  ** (Ecto.NoResultsError)
	
	"""
	
	def get_comment!(id), do: Repo.get!(Comment, id)


	@doc """
	Creates a comment.
	## Examples
	  iex> create_comment(%{field: value})
	  {:ok, %Comment{}}
	  iex> create_comment(%{field: bad_value})
	  {:error, %Ecto.Changeset{}}
	
	"""
	
	def create_comment(attrs \\ %{}) do
		%Comment{}
		|> Comment.changeset(attrs)
		|> Repo.insert()
	end


	@doc """
	Updates a comment.
	## Examples
	  iex> update_comment(comment, %{field: new_value})
	  {:ok, %Comment{}}
	  iex> update_comment(comment, %{field: bad_value})
	  {:error, %Ecto.Changeset{}}

	"""

	def update_comment(%Comment{} = comment, attrs) do
		comment
		|> Comment.changeset(attrs)
		|> Repo.update()
	end


	@doc """
	Deletes a Comment.
	## Examples
	  iex> delete_comment(comment)
	  {:ok, %Comment{}}
	  iex> delete_comment(comment)
	  {:error, %Ecto.Changeset{}}

	"""

	def delete_comment(%Comment{} = comment) do
		Repo.delete(comment)
	end


	@doc """
	Returns an `%Ecto.Changeset{}` for tracking comment changes.
	## Examples
	  iex> change_comment(comment)
	  %Ecto.Changeset{source: %Comment{}}

	"""

	def change_comment(%Comment{} = comment) do
		Comment.changeset(comment, %{})
	end

end

lib/comment_box/repo.ex
defmodule CommentBox.Repo do
  use Ecto.Repo, otp_app: :comment_box

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/comment_box_web/controllers/comment_controller.ex
defmodule CommentBoxWeb.CommentController do
	use CommentBoxWeb, :controller

	import Ecto.Changeset

	alias CommentBox.Comment
	alias CommentBox.Repo	
	alias CommentBox.Auth
    alias CommentBox.Auth.User

	def index(conn, _params) do
		comments = Comment.list_comments()
		users = Auth.list_users()
		render(conn, "index.html", comments: comments, users: users)
	end

	def show(conn, %{"id" => id}) do
		comment = Comment.get_comment!(id)
		render(conn, "show.html", comment: comment)
	end 

    def new(conn, _params) do
		changeset = change(%Comment{})
		users = Auth.list_users()
    	render(conn, "new.html", changeset: changeset, users: users)
    end

	def create(conn, %{"comment" => comment_params}) do
    	changeset = cast(%Comment{}, comment_params, [:title, :text, :owner, :parent])
		case Repo.insert(changeset) do
			{:ok, %Comment{}} ->
				conn
				|> put_flash(:info, "Created succefully!")
				|> redirect(to: page_path(conn, :index))
			{:error, changeset} ->
			    conn
				|> put_flash(:error, "Error creating comment")
				|> render("new.html", changeset: changeset)
		end		
    end    

    def edit(conn, %{"id" => id}) do
    	changeset = change(%Comment{})
    	render(conn, "reply.html", changeset: changeset, id: id)
    end     
end

lib/comment_box_web/controllers/page_controller.ex
defmodule CommentBoxWeb.PageController do
  use CommentBoxWeb, :controller

	alias CommentBox.Comment
	alias CommentBox.Auth
	alias CommentBox.Auth.User

	def index(conn, _params) do
		comments = Comment.list_comments()
		users = Auth.list_users()
		render(conn, "index.html", comments: comments, users: users)
	end
end

lib/comment_box_web/controllers/user_controller.ex
defmodule CommentBoxWeb.UserController do
	use CommentBoxWeb, :controller

	import Ecto.Changeset

    alias CommentBox.Auth
    alias CommentBox.Auth.User	

	def index(conn, _params) do
		users = Auth.list_users()
		render(conn, "index.html", users: users)   
	end

	def show(conn, %{"id" => id}) do
		user = Auth.get_user!(id)
		render(conn, "show.html", user: user)
	end 

    def new(conn, _params) do
    	changeset = change(%User{})
    	render(conn, "new.html", changeset: changeset)
    end

	def create(conn, %{"user" => user_params}) do
		with {:ok, %User{} = user} <- Auth.create_user(user_params) do
			conn
			|> put_flash(:info, "User created succefully!")
			|> redirect(to: user_path(conn, :index))
		end
	end
end

lib/comment_box_web/views/comment_view.ex
defmodule CommentBoxWeb.CommentView do
  use CommentBoxWeb, :view
end

lib/comment_box_web/views/error_view.ex
defmodule CommentBoxWeb.ErrorView do
  use CommentBoxWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/comment_box_web/views/layout_view.ex
defmodule CommentBoxWeb.LayoutView do
  use CommentBoxWeb, :view
end

lib/comment_box_web/views/page_view.ex
defmodule CommentBoxWeb.PageView do
  use CommentBoxWeb, :view
end

lib/comment_box_web/views/user_view.ex
defmodule CommentBoxWeb.UserView do
  use CommentBoxWeb, :view
end

lib/comment_box_web/templates/comment/new.html.eex
<div class="box-new-comment shadow mt-3">
	<%= form_for @changeset, comment_path(@conn, :create), fn f ->  %>
		<h3 class="title mb-3">New Comment</h3>
		<div class="form-group">
			<label class="w-100">
				Title: <%= text_input f, :title, class: "form-control" %>
			</label>
		</div>
		<div class="form-group">
			<label class="w-100">
				Text:<%= textarea f, :text, class: "form-control" %>
			</label>
		</div>
		<div class="form-group">
			<label class="w-100">
				<select name="owner" class="form-control"> 
					<option value="0">Select User</option>
					<%= for user <- @users do %>
						<option value="<%= user.id %>"><%= user.username %></option>
					<% end %>
				</select>
			</label>
		</div>
		<div class="text-right">
			<%= submit "Save Comment", class: "btn btn-primary" %>
		</div>
	<% end %>
</div>

lib/comment_box_web/templates/comment/reply.html.eex
<div class="box-new-comment shadow mt-3">
	<%= form_for @changeset, comment_path(@conn, :create), fn f ->  %>
		<h3 class="title mb-3">Reply to Comment</h3>
		<div class="form-group">
			<label>
				Title: <%= text_input f, :title, class: "form-control" %>
			</label>
		</div>
		<div class="form-group">
			<label>
				Text:<%= textarea f, :text, class: "form-control" %>
			</label>
		</div>
		<div class="form-group">
			<label>
				Owner: <%= number_input f, :owner, class: "form-control" %>
			</label>
		</div>

		<%= hidden_input f, :parent, value: @id %>
		
		<div class="text-right">
			<%= submit "Submit", class: "btn btn-primary" %>
		</div>
	<% end %>
</div>

lib/comment_box_web/templates/comment/show.html.eex
<div class="box-new-comment shadow mt-3">
	<h3 class="title">Comment by Id</h3>
	<div class="form-group mt-3">
		<label>
			Title: <%= @comment.title %>
		</label>
	</div>
	<div class="form-group">
		<label>
			Text: <%= @comment.text %>
		</label>
	</div>
	<div class="form-group">
		<label>
			Owner ID: <%= @comment.owner %>
		</label>
	</div>
	<div class="form-group">
		<label>
			Inserted At: <%= @comment.inserted_at %>
		</label>
	</div>
	<div class="form-group">
		<label>
			Updated At: <%= @comment.updated_at %>
		</label>
	</div>	
	<div class="text-right">	
	    <button type="button" class="btn btn-primary btn-sm">
	      <a href="<%= CommentBoxWeb.Router.Helpers.comment_path(CommentBoxWeb.Endpoint, :new) %>">Create a new Comment!</a>
	    </button>
    </div>
</div>

lib/comment_box_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CommentBox!</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">    
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">    
  </head>

  <body onmousemove="initTimeOut()">
    <div class="container">

      <p class="alert alert-info" id="success" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <header>
          <div class="container">
              <div class="row justify-content-center mt-4">
                  <div class="col-10">
                      <div class="header d-flex align-items-center justify-content-between">
                          <a href="/">
                              <img src="<%= static_path(@conn, "/images/logo.svg") %>" alt="">
                          </a>
                          <h1>Comment System</h1>
                      </div>
                  </div>
              </div>
              
          </div>
      </header>
      <header>

          <div class="container">
                <div class="row justify-content-center mt-4">
                    <div class="col-10">

                        <div class="header d-flex align-items-center justify-content-start my-3">
                            <a class="btn btn-primary" href="/">Comments</a>  <a class="btn btn-primary mx-2" href="/users">Users</a>
                        </div>
                    </div>
                </div>
          </div>

      </header>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script>
      let timeOut;

      function initTimeOut() {
        timeOut = setTimeout(hideFlashMessage, 3000);
      };

      function hideFlashMessage() {
        let element = document.getElementById("success");
        element.style.display = "none";
      };
    </script>
  </body>
</html>

lib/comment_box_web/templates/page/index.html.eex
<div id="content" class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-10">
            <div class="row">
                <div class="col-md-5">
                </div>
            </div>
        </div>
    </div>
</div>
<h4 class="title my-3">Comments</h4> 

<%= for comment <- @comments do %>

    <%= if !comment.parent do %>
        <div class="comment-box shadow">
            <div class="media">

                <%= for user <- @users do %>
                    <%= if user.id == comment.owner do %>
                        <div class="icon">
                            <span><%= user.username %></span>
                        </div>
                        <div class="media-body pt-2">
                            <h5 class="mt-0">
                                <%= user.username%>
                            </h5>
                            <span class="date">Added on: <%= comment.updated_at.month %>-<%= comment.updated_at.day %>-<%= comment.updated_at.year %><span>
                        </div>
                    <% end %>
                <% end %>

            </div>
            <div class="comment-content">
               
                <h3><a href="<%= CommentBoxWeb.Router.Helpers.comment_path(CommentBoxWeb.Endpoint, :show, comment.id) %>">Comment: <%= comment.title %></a></h3>
                <p><%= comment.text %></p>
                <!-- end of content -->

                <!-- REPLIES -->
                <%= for reply <- @comments do %>
                    <%= if reply.parent == comment.id do %>
                        <div class="box-reply">
                            <p><%= reply.text %></p>
                        </div>
                    <% end %>
                <% end %>
            
                <hr>
                <div class="reply-form">
                    <form action="">
                        <a href="<%= CommentBoxWeb.Router.Helpers.comment_path(CommentBoxWeb.Endpoint, :edit, comment.id) %>">Leave a Reply</a>
                        <button type="submit">
                            <img src="<%= static_path(@conn, "/images/Group 34.svg") %>" alt="">
                        </button>
                    </form>
                </div>
                
            </div>
        </div>

    <% end %>

<% end %>
<div class="text-right box-btn">
  <button type="button" class="btn btn-primary btn-sm">
    <a href="<%= CommentBoxWeb.Router.Helpers.comment_path(CommentBoxWeb.Endpoint, :new) %>">Create New Comment!</a>
  </button>
</div>

lib/comment_box_web/templates/user/index.html.eex
<div class="box-users py-2 shadow">
    <div class="users-header px-3">	
			<div class="col-lg-8">
					<h4 class="title">Users</h4>
					<ul class="users">
						<%= for user <- @users do %>
							<li class="user">
								<div class="media">
										<div class="icon">
												<span><%= user.username %></span>
										</div>
										<div class="media-body pt-3">
											<h5 class="mt-0"><a href="<%= CommentBoxWeb.Router.Helpers.user_path(CommentBoxWeb.Endpoint, :show, user.id) %>">Name: <%= user.username %></a></h5>
											<a href="mailto:<%= user.email %>" class="my-2 email"><%= user.email %></a>
										</div>
								</div>
							</li>
					
						<% end %>	
					</ul>
			</div>
	</div>
	<div class="text-right box-btn">
		<button type="button" class="btn btn-primary mr-3 btn-sm">
			<a href="<%= CommentBoxWeb.Router.Helpers.user_path(CommentBoxWeb.Endpoint, :new) %>">Create New User!</a>
		</button>
	</div>
</div>

lib/comment_box_web/templates/user/new.html.eex
<div class="box-new-comment shadow mt-3">
	<%= form_for @changeset, user_path(@conn, :create), fn f ->  %>
		<h3 class="title mb-3">New User</h3>
		<div class="form-group mt-3">
			<label class="w-100">
				Username: <%= text_input f, :username, class: "form-control" %>
			</label>
		</div>
		<div class="form-group">
			<label class="w-100">
				Email: <%= email_input f, :email, class: "form-control" %>
			</label>
		</div>
		<div class="form-group">
			<label class="w-100">
				Password:<%= password_input f, :password, class: "form-control" %>
			</label>
		</div>
		<div class="text-right">		
			<%= submit "Create User", class: "btn btn-primary" %>
		</div>
	<% end %>
</div>

lib/comment_box_web/templates/user/show.html.eex
<div class="box-new-comment shadow mt-3">
	<h3 class="title mb-3">User by Id</h3>
	<div class="form-group">
		<label>
			Name: <%= @user.username %>
		</label>
	</div>
	<div class="form-group">
		<label>
			Email: <%= @user.email %>
		</label>
	</div>
	<div class="form-group">
		<label>
			ID: <%= @user.id %>
		</label>
	</div>
	<div class="form-group">
		<label>
			Is Active: <%= @user.is_active %>
		</label>
	</div>
	<div class="form-group">
		<label>
			Inserted At: <%= @user.inserted_at %>
		</label>
	</div>
	<div class="form-group">
		<label>
			Updated At: <%= @user.updated_at %>
		</label>
	</div>
	<div class="text-right">		
	    <button type="button" class="btn btn-primary btn-sm">
	      <a href="<%= CommentBoxWeb.Router.Helpers.comment_path(CommentBoxWeb.Endpoint, :new) %>">Create a new User!</a>
	    </button>  
    </div> 
</div>